src/carts/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success', checkout_done_view, name='success'),

]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from carts.views import cart_detail_api_view
from . import views
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from billing.views import payment_method_view, payment_method_createview
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

# from products.views import ProductListView , ProductDetailView , ProductFeaturedListView ,
#  ProductFeaturedDetailView , ProductDetailSlugView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/guest', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('cart/api/cart/', cart_detail_api_view, name='api-cart'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('contact/', views.contact, name='contact'),
    path('checkout/address/create', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('cart/', include(('carts.urls', 'carts'), namespace='cart')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import ProductListView , ProductDetailView , ProductFeaturedListView , ProductFeaturedDetailView , ProductDetailSlugView
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='details'),
    #path('featured/', ProductFeaturedListView.as_view()),
    #path('featured/<int:pk>/', ProductFeaturedDetailView.as_view()),
    #path('products/<int:pk>/', ProductDetailView.as_view()),
]

src/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
      integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static "css/main.css" %}"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
      integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


<!--jquery confirm css !-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">


<!-- stripe-->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

src/templates/base/forms.html
{% extends "base.html" %}


{% block content %}
    <div class="col-12 col-md-6 mx-auto">
        {% if title %}<h2 class="my-3">{{ title }}</h2>{% endif %}
        <form method="post" action="{% if action_url %}{{ action_url }}{% endif %}">
            {% csrf_token %}
            {% if next_url %}
                <input type="hidden" name="next" value="{{ next_url }}">
            {% endif %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-default">Save</button>

        </form>
    </div>
{% endblock %}

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous">

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<!--stripe js!-->
<script src="https://js.stripe.com/v3/"></script>


<!-- jquery confirm js!-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!--render js!-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.1/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!-- django security ajax js!-->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- ecommerce js!-->
<script src="{% static 'js/ecommerce.js' %}"></script>

<!-- ecommerce main js!-->
<script src="{% static 'js/ecommerce.main.js' %}"></script>

src/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form!-->
<script id="stripeTemplate" type="text/x-jsrender">
            <form class='payment-form' action="" method="post" id="payment-form" data-token="{{:publishKey}}"
              data-next-url="{{:nextUrl}}">
            <div class="form-row">
                <div id="card-element" class="form-control">
                </div>

                <div id="card-errors" role="alert"></div>
            </div>

            <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
        </form>




</script>
{% endverbatim %}

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_url %}
{% url 'cart:home' as cart_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            {% if brand_name %}{{ brand_name }}{% else %}eCommerrrce{% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Login and Register
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item {% if request.path == product_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_url }}">Products</a>
                </li>
                <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                    <a class="nav-link" href="{{ cart_url }}"><i class="fab fa-opencart"></i> <span
                            class="navbar-cart-count">({{ request.session.cart_items }})</span></a>
                </li>
            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>